/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "stm32f429zi.h"
#include <stdint.h>
#include <string.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
void	delay(void){
	for(uint32_t i=0;i<500000/2;i++);
}
#define 	BTN_PRESSED	HIGH
#define		HIGH		1
#define		LOW			0
int main(void)
{
	GPIO_Handle_t	GpioLed,GpioBtn;
	memset(&GpioLed,0,sizeof(GpioLed));
	memset(&GpioBtn,0,sizeof(GpioBtn));
	GpioLed.pGPIOx=GPIOD;
	GpioLed.GPIO_PinConfig.GPIO_PinNumber	=GPIO_PIN_NO_12;
	GpioLed.GPIO_PinConfig.GPIO_PinMode		=GPIO_MODE_OUT;
	GpioLed.GPIO_PinConfig.GPIO_PinSpeed	=GPIO_SPEED_LOW;
	GpioLed.GPIO_PinConfig.GPIO_PinOPType	=GPIO_OP_TYPE_PP;
	GpioLed.GPIO_PinConfig.GPIO_PinPuPdControl=GPIO_NO_PUPD;
	GPIO_PeriClockControl(GPIOD, ENABLE);
	GPIO_Init(&GpioLed);

	GpioBtn.pGPIOx=GPIOD;
		GpioBtn.GPIO_PinConfig.GPIO_PinNumber	=GPIO_PIN_NO_5;
		GpioBtn.GPIO_PinConfig.GPIO_PinMode		=GPIO_MODE_IT_FT;
		GpioBtn.GPIO_PinConfig.GPIO_PinSpeed	=GPIO_SPEED_FAST;
		GpioBtn.GPIO_PinConfig.GPIO_PinPuPdControl=GPIO_PIN_PU;
		GPIO_PeriClockControl(GPIOD, ENABLE);
		GPIO_Init(&GpioBtn);
		//IRQ CONFIG
		GPIO_IRQPriorityConfig(IRQ_NO_EXTI9_5, NVIC_IRQ_PRI15);
		GPIO_IRQConfig(IRQ_NO_EXTI9_5, ENABLE);
while(1);
}
		void EXTI9_5_IRQHandler(void) {
			delay();
			GPIO_IRQHandling(GPIO_PIN_NO_5);
			GPIO_TogglePin(GPIOD, GPIO_PIN_NO_12);
		}


