/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "stm32f429zi.h"
#include <stdint.h>
#include <string.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
void	delay(void){
	for(uint32_t i=0;i<500000/2;i++);
}
#define 	BTN_PRESSED	HIGH
#define		LED_ON		1
#define		LED_OFF			0
#define	COMMAND_LED_CTRL	0X50
#define	COMMAND_SENSOR_READ	0X51
#define	COMMAND_LED_READ	0X52
#define	COMMAND_PRINT	0X53
#define	COMMAND_ID_READ	0X54
//arduino analog pins
#define ANALOG_PIN0	0
#define ANALOG_PIN1	1
#define ANALOG_PIN2	2
#define ANALOG_PIN3	3
#define ANALOG_PIN4	4

//ARDUINO LED
#define LED_PIN	9
/*
 * PB14->SPI2_MISO
 * PB15->SPI2_MOSI
 * PB13->SPI2_SCLK
 * PB12->SPI2_NSS
 * ALT FUNCTION MODE: 5
 */
void GPIO_ButtonInit(void){
	GPIO_Handle_t	GpioBtn;
	GpioBtn.pGPIOx=GPIOA;
			GpioBtn.GPIO_PinConfig.GPIO_PinNumber	=GPIO_PIN_NO_0;
			GpioBtn.GPIO_PinConfig.GPIO_PinMode		=GPIO_MODE_IN;
			GpioBtn.GPIO_PinConfig.GPIO_PinSpeed	=GPIO_SPEED_FAST;
			GpioBtn.GPIO_PinConfig.GPIO_PinPuPdControl=GPIO_PIN_NO_PUPD;

			GPIO_Init(&GpioBtn);
}
void SPI_GPIOInits(void){
	GPIO_Handle_t SPIPins;
	SPIPins.pGPIOx=GPIOB;
	SPIPins.GPIO_PinConfig.GPIO_PinMode=GPIO_MODE_ALTFN;
	SPIPins.GPIO_PinConfig.GPIO_PinAltFunMode=5;
	SPIPins.GPIO_PinConfig.GPIO_PinOPType=GPIO_OP_TYPE_PP;
	SPIPins.GPIO_PinConfig.GPIO_PinPuPdControl=GPIO_PIN_NO_PUPD;
	SPIPins.GPIO_PinConfig.GPIO_PinSpeed=GPIO_SPEED_FAST;
	//SCLK
	SPIPins.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_13;
	GPIO_Init(&SPIPins);
	//MOSI
		SPIPins.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_15;
		GPIO_Init(&SPIPins);
		//NSS
			SPIPins.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_12;
			GPIO_Init(&SPIPins);
			//MISO
				SPIPins.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_14;
				GPIO_Init(&SPIPins);

}
void SPI2_Inits(){
	SPI_Handle_t	SPI2handle;
	SPI2handle.pSPIx=SPI2;
	SPI2handle.SPIConfig.SPI_BusConfig=SPI_BUS_CONFIG_FD;
	SPI2handle.SPIConfig.SPI_DeviceMode=SPI_DEVICE_MODE_MASTER;
	SPI2handle.SPIConfig.SPI_SclkSpeed=SPI_SCLK_SPEED_DIV8;
	SPI2handle.SPIConfig.SPI_DFF=SPI_DFF_8BITS;
	SPI2handle.SPIConfig.SPI_CPOL=SPI_CPOL_LOW;
	SPI2handle.SPIConfig.SPI_CPHA=SPI_CPHA_LOW;
	SPI2handle.SPIConfig.SPI_SSM=SPI_SSM_DI;//HW SLAVE MANAGEMENT ENABLE
	SPI_Init(&SPI2handle);
}
uint8_t SPI_VerifyResponse(uint8_t ackbyte){
	if(ackbyte==0xF5){
		//ack
		return 1;
	}
	return 0;
}
extern void initialise_monitor_handles(void);
int main(void)
{
	initialise_monitor_handles();
	printf("application is running\n");
	uint8_t	dummy_write=0xff;
	uint8_t	ackbyte;
	uint8_t	dummy_read;
		uint8_t args[2];
	char user_data[]="Hello world";
	SPI_GPIOInits();
	SPI2_Inits();
	SPI_SSOEConfig(SPI2, ENABLE);
	while(1){
		//wait till button is pressed
	while(!GPIO_ReadFromInputPin(GPIOA, GPIO_PIN_NO_0));
	delay();
	//enable spi2 peripheral
	SPI_PeripheralControl(SPI2,ENABLE);
	//1.CMDLEDCTRL
	uint8_t	commndcode=COMMAND_LED_CTRL;
	SPI_SendData(SPI2, &commndcode, 1);
	//do dummy read to clear of the RXNE
		SPI_ReceiveData(SPI2, &dummy_read, 1);
	//send some dummy
	SPI_SendData(SPI2,&dummy_write,1);


	SPI_ReceiveData(SPI2, &ackbyte, 1);
	if(SPI_VerifyResponse(ackbyte))
	{
		//send argument
		args[0]=LED_PIN;
		args[1]=LED_ON;
		SPI_SendData(SPI2, args, 2);
	}
	//end of commandledctrl

	//command_sensor_read
	//wait till button is pressed
		while(!GPIO_ReadFromInputPin(GPIOA, GPIO_PIN_NO_0));
		delay();
		commndcode=COMMAND_SENSOR_READ;
		//send command
		SPI_SendData(SPI2, &commndcode, 1);
		//do dummy read to clear of the RXNE
				SPI_ReceiveData(SPI2, &dummy_read, 1);
			//send some dummy
			SPI_SendData(SPI2,&dummy_write,1);


			SPI_ReceiveData(SPI2, &ackbyte, 1);
			if(SPI_VerifyResponse(ackbyte))
			{
				//send argument
				args[0]=ANALOG_PIN0;

				SPI_SendData(SPI2, args, 1);

				//do dummy read to clear of the RXNE
					SPI_ReceiveData(SPI2, &dummy_read, 1);
					//insert some delay so slave can read the data
					delay();
					//send dummy bits (1 byte) fetch the response from slave
					SPI_SendData(SPI2, &dummy_write, 1);
					uint8_t	analog_read;
					SPI_ReceiveData(SPI2, &analog_read, 1);
						//end of command_sensor_read

			}




	//First send length info
	uint8_t dataLen= strlen(user_data);
	SPI_SendData(SPI2,&dataLen,1);
	//send data
	SPI_SendData(SPI2,(uint8_t*) user_data, strlen(user_data));
	//if tx ended

	while(SPI_GetFlagStatus(SPI2, SPI_SR_BSY));
	//disable peripheral
	SPI_PeripheralControl(SPI2,DISABLE);
	}
	return 0;
}

