/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "stm32f429zi.h"
#include <stdint.h>
#include <string.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
void	delay(void){
	for(uint32_t i=0;i<50000;i++);
}
I2C_Handle_t	I2C1Handle,I2C2Handle;

#define		HIGH	1
#define 	BTN_PRESSED	HIGH
#define		LED_ON		1
#define		LED_OFF			0
#define 	SLAVE_ADDRRESS 0x1
#define 	MY_ADDR		0x2
#define LED_PIN	9
uint16_t pinn=33;
static uint8_t commandCode =0;
static uint8_t Cnt=0;
//some data
uint8_t rcv_buff[7];
//some data
uint8_t TX_buff[7];
uint8_t rxcomplt;
uint8_t	led1_st=0;
uint8_t	led2_st=0;
uint8_t	led3_st=0;
uint8_t	led4_st=0;
uint8_t	led5_st=0;
uint8_t lasteff=6;
uint8_t	commandcode=0;
/*
 * PB6->SCL
 * PB9->SDA
 * PB13->SPI2_SCLK
 * PB12->SPI2_NSS
 * ALT FUNCTION MODE: 5
 * PD8->LED1
 * PD9->LED2
 * PD10->LED3
 * PD11->LED4
 * PD12->LED5
 */




void GPIO_ButtonInit(void){
	GPIO_Handle_t	GpioBtn,GpioLed;
	memset(&GpioLed,0,sizeof(GpioLed));
		memset(&GpioBtn,0,sizeof(GpioBtn));
	GpioBtn.pGPIOx=GPIOA;
			GpioBtn.GPIO_PinConfig.GPIO_PinNumber	=GPIO_PIN_NO_0;
			GpioBtn.GPIO_PinConfig.GPIO_PinMode		=GPIO_MODE_IT_FT;
			GpioBtn.GPIO_PinConfig.GPIO_PinSpeed	=GPIO_SPEED_FAST;
			GpioBtn.GPIO_PinConfig.GPIO_PinPuPdControl=GPIO_PIN_PU;
			GPIO_Init(&GpioBtn);
			GpioBtn.GPIO_PinConfig.GPIO_PinNumber	=GPIO_PIN_NO_1;
			GPIO_Init(&GpioBtn);
			GpioBtn.GPIO_PinConfig.GPIO_PinNumber	=GPIO_PIN_NO_7;
			GPIO_Init(&GpioBtn);
			GpioBtn.GPIO_PinConfig.GPIO_PinNumber	=GPIO_PIN_NO_3;
			GPIO_Init(&GpioBtn);
			GpioBtn.GPIO_PinConfig.GPIO_PinNumber	=GPIO_PIN_NO_4;
			GPIO_Init(&GpioBtn);
			GpioBtn.GPIO_PinConfig.GPIO_PinNumber	=GPIO_PIN_NO_5;
			GPIO_Init(&GpioBtn);
			GpioBtn.GPIO_PinConfig.GPIO_PinNumber	=GPIO_PIN_NO_6;
			GPIO_Init(&GpioBtn);

			GpioLed.pGPIOx=GPIOD;
						GpioLed.GPIO_PinConfig.GPIO_PinNumber	=GPIO_PIN_NO_12;
						GpioLed.GPIO_PinConfig.GPIO_PinMode		=GPIO_MODE_OUT;

						GpioLed.GPIO_PinConfig.GPIO_PinSpeed	=GPIO_SPEED_LOW;
						GpioLed.GPIO_PinConfig.GPIO_PinOPType	=GPIO_OP_TYPE_PP;
						GpioLed.GPIO_PinConfig.GPIO_PinPuPdControl=GPIO_NO_PUPD;
						GPIO_Init(&GpioLed);
						GpioLed.GPIO_PinConfig.GPIO_PinNumber	=GPIO_PIN_NO_11;
						GPIO_Init(&GpioLed);
						GpioLed.GPIO_PinConfig.GPIO_PinNumber	=GPIO_PIN_NO_13;
						GPIO_Init(&GpioLed);
						GpioLed.GPIO_PinConfig.GPIO_PinNumber	=GPIO_PIN_NO_7;
						GPIO_Init(&GpioLed);
						GpioLed.GPIO_PinConfig.GPIO_PinNumber	=GPIO_PIN_NO_6;
						GPIO_Init(&GpioLed);
}

void I2C_GPIOInits(void){
GPIO_Handle_t	I2CPins;
I2CPins.pGPIOx=GPIOB;
I2CPins.GPIO_PinConfig.GPIO_PinMode=GPIO_MODE_ALTFN;
I2CPins.GPIO_PinConfig.GPIO_PinOPType=GPIO_OP_TYPE_OD;
I2CPins.GPIO_PinConfig.GPIO_PinPuPdControl=GPIO_PIN_PU;
I2CPins.GPIO_PinConfig.GPIO_PinAltFunMode=4;
I2CPins.GPIO_PinConfig.GPIO_PinSpeed=GPIO_SPEED_FAST;



//SCL1
I2CPins.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_8;
GPIO_Init(&I2CPins);
//SDA1
I2CPins.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_9;
GPIO_Init(&I2CPins);
//SCL2
I2CPins.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_10;
GPIO_Init(&I2CPins);
//SDA2
I2CPins.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_11;
GPIO_Init(&I2CPins);

}
void I2C1_Inits(){

	I2C1Handle.pI2Cx = I2C1;
		I2C1Handle.I2C_Config.I2C_AckControl = I2C_ACK_ENABLE;
		I2C1Handle.I2C_Config.I2C_DeviceAddress = 0x01;
		I2C1Handle.I2C_Config.I2C_FMDutyCycle = I2C_FM_DUTY_2;
		I2C1Handle.I2C_Config.I2C_SCLSpeed = I2C_SCL_SPEED_SM;

		I2C_Init(&I2C1Handle);
}
void I2C2_Inits(){

	I2C2Handle.pI2Cx=I2C2;
	I2C2Handle.I2C_Config.I2C_AckControl=I2C_ACK_ENABLE;
	I2C2Handle.I2C_Config.I2C_DeviceAddress=0x01;
	I2C2Handle.I2C_Config.I2C_SCLSpeed=I2C_FM_DUTY_2;
	I2C2Handle.I2C_Config.I2C_SCLSpeed=I2C_SCL_SPEED_SM;
	I2C_Init(&I2C2Handle);
}
extern void initialise_monitor_handles(void);
int main(void)
{
	initialise_monitor_handles();
	printf("Application is running\n");

	//i2c configs
	//button
	GPIO_ButtonInit();
	//i2c pin
	I2C_GPIOInits();
	//IRQ CONFIG


/*
			GPIO_IRQPriorityConfig(IRQ_NO_EXTI0, NVIC_IRQ_PRI15); //ALGO LE PASA INVESTIGAR
			GPIO_IRQConfig(IRQ_NO_EXTI0, ENABLE);



			GPIO_IRQPriorityConfig(IRQ_NO_EXTI1, NVIC_IRQ_PRI15);
			GPIO_IRQConfig(IRQ_NO_EXTI1, ENABLE);

			GPIO_IRQPriorityConfig(IRQ_NO_EXTI2, NVIC_IRQ_PRI15);
			GPIO_IRQConfig(IRQ_NO_EXTI2, ENABLE);

			GPIO_IRQPriorityConfig(IRQ_NO_EXTI4, NVIC_IRQ_PRI15);
			GPIO_IRQConfig(IRQ_NO_EXTI4, ENABLE);
			*/


	//i2c peri confg
	I2C1_Inits();
	I2C2_Inits();
	//i2c irq config
	I2C_IRQInterruptConfig(IRQ_NO_I2C1_EV, ENABLE);
	I2C_IRQInterruptConfig(IRQ_NO_I2C1_ER, ENABLE);
	I2C_IRQInterruptConfig(IRQ_NO_I2C2_EV, ENABLE);
	I2C_IRQInterruptConfig(IRQ_NO_I2C2_ER, ENABLE);
	I2C_SlaveEnableDisableCallbackEvents(I2C2,ENABLE);
	//I2C PERI ENABLE
	I2C_PeripheralControl(I2C1, ENABLE);
	I2C_PeripheralControl(I2C2, ENABLE);
	//ACK BIT MADE 1 AFTER PE=1
	I2C_ManageAcking(I2C1, I2C_ACK_ENABLE);
	I2C_ManageAcking(I2C2, I2C_ACK_ENABLE);
//this is what CAN SHOULD SEND BUT WE SETUP FOR I2C TESTING
	//BUTTONS TO DO FUNCTIONS

	while(1){

		GPIO_IRQPriorityConfig(IRQ_NO_EXTI3, NVIC_IRQ_PRI15);
					GPIO_IRQConfig(IRQ_NO_EXTI3, ENABLE);
		//GPIO_IRQPriorityConfig(IRQ_NO_EXTI9_5, NVIC_IRQ_PRI15);
			//		GPIO_IRQConfig(IRQ_NO_EXTI9_5, ENABLE);
while(pinn==33){											//we sample buttons

}

		//a button was determined as pressed we setup the msg
		GPIO_CUSTOMINTERRUPT(pinn);
		//send the data to slave through i2c1 to i2c2(slave)
		commandcode=0x51;

			I2C_MasterSendData(&I2C1Handle, &commandcode, 1, SLAVE_ADDRRESS,I2C_ENABLE_SR);
		I2C_MasterReceiveData(&I2C1Handle, TX_buff,strlen((char*)TX_buff) , SLAVE_ADDRRESS,I2C_DISABLE_SR);

		//wait for data from slave

		I2C_MasterReceiveData(&I2C1Handle, rcv_buff, strlen((char*)rcv_buff), SLAVE_ADDRRESS, I2C_DISABLE_SR);
		//if we recieve we toggle one led
		while(strlen((char*)rcv_buff)>6);

		GPIO_TogglePin(GPIOD, GPIO_PIN_NO_13);
			}


}

void I2C1_EV_IRQHandler (){
I2C_EV_IRQHandling(&I2C1Handle);
}
void I2C1_ER_IRQHandler (){
	I2C_ER_IRQHandling(&I2C1Handle);
}
void 	I2C_ApplicationEventCallback(I2C_Handle_t *pI2CHandle, uint8_t AppEv){
	if(AppEv==I2C_EV_DATA_REQ)  {
		//Master wants some data that slave has to send
		if(commandCode==0x51){
			//send the length info to the master
			I2C_SlaveSendData(pI2CHandle->pI2Cx, strlen((char*)TX_buff));
		}else if(commandCode==0x52){
				//Send the contents of Tx_buf
				I2C_SlaveSendData(pI2CHandle->pI2Cx, TX_buff[Cnt++]);
			}

	}else if(AppEv==I2C_EV_DATA_RCV){

		//data is waiting for the slave to read.slave has to read it
	commandCode =I2C_SlaveReceiveData(pI2CHandle->pI2Cx);


	}	else if(AppEv==I2C_EV_TX_CMPLT)  {
	printf("Tx is completed\n");
}else if(AppEv==I2C_EV_RX_CMPLT){
	printf("Rx is completed\n");
	rxcomplt=SET;
}else if(AppEv==I2C_ERROR_AF){
	printf("Error : Ack failure\n");
	//in master ack failure happens when salve fails to send
	//ack for the bit sent from the master
	commandCode=0xff;
	Cnt=0;
	I2C_CloseSendData(pI2CHandle);
	//generate stop condition
I2C_GenerateStopCondition(I2C1);
//hang in infinite loop
while(1);
}else if(AppEv==I2C_EV_STOP){
	//only during slave reception
	//master has ended i2c comm with slave
}
}



void GPIO_CUSTOMINTERRUPT(uint16_t pinN){
	 if(pinN==GPIO_PIN_NO_0){
		//send msg to set alarm
		 TX_buff[0]=1;
		 		TX_buff[1]=1;
	}else if(pinN==GPIO_PIN_NO_1){
		//send msg to toggle pin1
		TX_buff[0]=0;
		TX_buff[1]=0;//single led
		TX_buff[2]=1;//LED ID
		TX_buff[3]=0;//LED ID
		TX_buff[4]=0;//LED ID
		if(led1_st==0){
			TX_buff[5]=1;	 //TOGGLE msg
		}else{
			TX_buff[5]=0;	 //TOGGLE msg
		}

	}else if(pinN==GPIO_PIN_NO_2){
		//send msg to toggle pin2
		TX_buff[0]=0;
				TX_buff[1]=0;//single led
				TX_buff[2]=0;//LED ID
				TX_buff[3]=1;//LED ID
				TX_buff[4]=0;//LED ID
				if(led2_st==0){
					TX_buff[5]=1;	 //TOGGLE msg
				}else{
					TX_buff[5]=0;	 //TOGGLE msg
				}
	}else if(pinN==GPIO_PIN_NO_3){
		//send msg to toggle pin3
		TX_buff[0]=0;
				TX_buff[1]=0;//single led
				TX_buff[2]=1;//LED ID
				TX_buff[3]=1;//LED ID
				TX_buff[4]=0;//LED ID
				if(led3_st==0){
					TX_buff[5]=1;	 //TOGGLE msg
				}else{
					TX_buff[5]=0;	 //TOGGLE msg
				}
	}else if(pinN==GPIO_PIN_NO_4){
		//send msg to toggle pin4
		TX_buff[0]=0;
				TX_buff[1]=0;//single led
				TX_buff[2]=0;//LED ID
				TX_buff[3]=0;//LED ID
				TX_buff[4]=1;//LED ID
				if(led4_st==0){
					TX_buff[5]=1;	 //TOGGLE msg
				}else{
					TX_buff[5]=0;	 //TOGGLE msg
				}
	}else if(pinN==GPIO_PIN_NO_5){
		//send msg to toggle pin5
		TX_buff[0]=0;
				TX_buff[1]=0;//single led
				TX_buff[2]=1;//LED ID
				TX_buff[3]=0;//LED ID
				TX_buff[4]=1;//LED ID
				if(led5_st==0){
					TX_buff[5]=1;	 //TOGGLE msg
				}else{
					TX_buff[5]=0;	 //TOGGLE msg
				}
	}else if(pinN==GPIO_PIN_NO_6){
		//send msg to toggle modes
		TX_buff[0]=1;
				TX_buff[1]=0;//single led
				if(lasteff==6){//first trigger of modes
				TX_buff[2]=0;//LED ID
				TX_buff[3]=0;//LED ID
				lasteff=0;
				}else if(lasteff==0){//we cycle through modes
					TX_buff[2]=1;//LED ID
					TX_buff[3]=0;//LED ID
					lasteff++;
				}else if(lasteff==1){
					TX_buff[2]=0;//LED ID
					TX_buff[3]=1;//LED ID
					lasteff++;
				}else if(lasteff==2){
					TX_buff[2]=1;//LED ID
					TX_buff[3]=1;//LED ID
					lasteff=6;
				}



	}

}
void EXTI9_5_IRQHandler(void) {
			delay();
			GPIO_IRQHandling(GPIO_PIN_NO_5);
			GPIO_TogglePin(GPIOD, GPIO_PIN_NO_12);
			pinn=5;
		}
void EXTI0_IRQHandler(void) {
			delay();
			GPIO_IRQHandling(GPIO_PIN_NO_0);
			pinn=0;
		}
void EXTI1_IRQHandler(void) {
			delay();
			GPIO_IRQHandling(GPIO_PIN_NO_2);
			pinn=1;
		}
void EXTI3_IRQHandler(void) {
			delay();
			GPIO_IRQHandling(GPIO_PIN_NO_3);
			GPIO_TogglePin(GPIOD, GPIO_PIN_NO_12);
			pinn=3;
		}
void EXTI4_IRQHandler(void) {
			delay();
			GPIO_IRQHandling(GPIO_PIN_NO_4);
			pinn=4;
		}

